"""Add adhar_no to users table

Revision ID: b19822f50c4e
Revises: 
Create Date: 2025-08-15 23:54:23.609522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b19822f50c4e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_role', sa.Enum('admin', 'user', 'guest', name='userrole'), nullable=False, 
                                     server_default='user'))
    op.add_column('users', sa.Column('adhar_no', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'adhar_no')
    op.drop_column('users', 'user_role')
    # ### end Alembic commands ###
