"""Add user-item relationship

Revision ID: e1bc07c66b1e
Revises: b19822f50c4e
Create Date: 2025-08-16 09:21:28.517203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1bc07c66b1e'
down_revision: Union[str, Sequence[str], None] = 'b19822f50c4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_items_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_items_user_id_users', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_items_user_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_items_user_id'))
        batch_op.drop_column('user_id')
    # ### end Alembic commands ###
